openapi: 3.1.0
info:
  title: Item Schema
  version: 1.0.0
components:
  schemas:
    Item:
      type: object
      required:
        - code
      properties:
        code:
          type: string
        quantity:
          type: number
          format: float
      additionalProperties: false
